tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "universal-ctags/universal-ctags"
cask "java" unless system "/usr/libexec/java_home --failfast"
cask "xquartz"
brew "adns"
brew "libpng"
brew "freetype"
brew "gettext"
brew "libffi"
brew "pcre"
brew "pixman"
brew "cairo"
brew "fribidi"
brew "jpeg"
brew "gdk-pixbuf"
brew "graphite2"
brew "icu4c"
brew "libcroco"
brew "librsvg"
brew "adwaita-icon-theme"
brew "openssl"
brew "alpine"
brew "ant"
brew "libnet"
brew "arping"
brew "asciidoc"
brew "dbus"
brew "at-spi2-core"
brew "at-spi2-atk"
brew "readline"
brew "autoconf"
brew "automake"
brew "byacc"
brew "c-ares"
brew "ccat"
brew "cdpr"
brew "chezscheme"
brew "chicken"
brew "rlwrap"
brew "clojure"
brew "clozure-cl"
brew "cmake"
brew "cmark"
brew "dhcpdump"
brew "dialog"
brew "diction"
brew "libgpg-error"
brew "libassuan"
brew "libgcrypt"
brew "libksba"
brew "pth"
brew "dirmngr"
brew "dos2unix"
brew "gmp"
brew "libunistring"
brew "nettle"
brew "gnutls"
brew "emacs"
brew "lame"
brew "x264"
brew "xvid"
brew "xz"
brew "ffmpeg"
brew "fping"
brew "fzf"
brew "gauche"
brew "webp"
brew "gd"
brew "gdbm"
brew "geoip"
brew "libtool"
brew "gforth"
brew "git"
brew "git-lfs"
brew "sqlite"
brew "python"
brew "glances"
brew "libsigsegv"
brew "gnu-smalltalk"
brew "libusb"
brew "npth"
brew "pinentry"
brew "gnupg"
brew "go"
brew "pkg-config"
brew "python@2"
brew "gobject-introspection"
brew "gotags"
brew "gpg-agent"
brew "graphviz"
brew "grv"
brew "gsettings-desktop-schemas"
brew "libepoxy"
brew "gtk+3"
brew "guile"
brew "hping"
brew "httping"
brew "hyperspec"
brew "ifstat"
brew "intltool"
brew "iperf3"
brew "json-c"
brew "leiningen"
brew "lft"
brew "lftp"
brew "libdnet"
brew "libevent"
brew "libiconv"
brew "libyaml"
brew "ruby", link: true
brew "libusb-compat"
brew "libxml2"
brew "libxslt"
brew "lldpd"
brew "m-cli"
brew "macvim"
brew "markdown"
brew "mas"
brew "masscan"
brew "md5deep"
brew "minicom"
brew "minimal-racket"
brew "mtr"
brew "ncdu"
brew "ncurses"
brew "neon"
brew "nethack"
brew "newsboat"
brew "nfdump"
brew "nmap"
brew "openssl@1.1"
brew "packer"
brew "pandoc"
brew "paperkey"
brew "pidof"
brew "poppler"
brew "procmail"
brew "qemu"
brew "rclone"
brew "resty"
brew "ripgrep"
brew "rsync"
brew "scons"
brew "sf-pwgen"
brew "smartmontools"
brew "smartypants"
brew "sslscan"
brew "stunnel"
brew "tcping"
brew "tcptraceroute"
brew "telnet"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "transmission"
brew "trash"
brew "tree"
brew "unixodbc"
brew "vim"
brew "vimpager"
brew "w3m"
brew "watch"
brew "weechat"
brew "wget"
brew "wiki"
brew "wireshark", link: false
brew "wxmac"
brew "yadm"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
cask "box-sync"
cask "boxer"
cask "google-chrome"
cask "java"
cask "firefox"
cask "keybase"
cask "macdown"
cask "manopen"
cask "nanostudio"
cask "nvalt"
cask "openemu"
cask "omnigraffle"
cask "parallels"
cask "parallels-virtualization-sdk"
cask "steam"
cask "spotify"
cask "tigervnc-viewer"
cask "torbrowser"
cask "transmission"
cask "teamviewer"
cask "vagrant"
cask "vcv-rack"
cask "wireshark"
cask "wkhtmltopdf"
cask "xscreensaver"
cask "yujitach-menumeters"
mas "1Password", id: 443987910
mas "Apple Configurator 2", id: 1037126344
mas "Calca", id: 635758264
mas "GhosteryLite", id: 1436953057
mas "Graphic", id: 404705039
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "Magnet", id: 441258766
mas "Marked 2", id: 890031187
mas "Microsoft Remote Desktop", id: 715768417
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator", id: 407963104
mas "Slack", id: 803453959
mas "The Unarchiver", id: 425424353
mas "Todoist", id: 585829637
mas "Tomato One", id: 907364780
mas "WiFi Explorer", id: 494803304
